app = "coc-excel-export"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true

  [http_service.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 25
